name: maths
description: Advanced Math library for Dart with support for Complex, FFT and Convolutions.
version: 0.0.1
repository: https://github.com/xclud/dart_maths
homepage: https://pwa.ir

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.22.0
  lints: ^2.0.0
